// Code generated by Slice Machine. DO NOT EDIT.

import CoverImage from './CoverImage';
import NavigationItem from './NavigationItem';

export {
	CoverImage,
	NavigationItem,
};

export const components = {
	cover_image: CoverImage,
	navigation_item: NavigationItem,
};
